# Generated by Django 5.2.6 on 2025-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='heatmap_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
